if(document.location.href=="file:///D:/%D0%91%D0%93%D0%A2%D0%A3/%D0%94%D0%AD%D0%B8%D0%92%D0%98/%D0%9A%D0%9F/%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0/index.html"||document.location.href=="http://127.0.0.1:5500/index.html"||document.location.href=="https://olegpazny.github.io/DriveAuto/"||document.location.href=="http://127.0.0.1:5500/index.html#"){
    document.write('<footer>');
    document.write('        <div class="footer-container">');
    document.write('            <div class="links-container">');
    document.write('                <div class="links-row">');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Автомобили с пробегом</p>');
    document.write('                        <a href="404.html"><p>Автомобили с большим пробегом</p></a>');
    document.write('                        <a href="404.html"><p>Автомобили "как с салона"</p></a>');
    document.write('                        <a href="404.html"><p>Сервис Trade-In</p></a>');
    document.write('                    </div>');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Владельцам</p>');
    document.write('                        <a href="404.html"><p>Услуги сервиса</p></a>');
    document.write('                        <a href="404.html"><p>Запасные масла и расходники</p></a>');
    document.write('                        <a href="404.html"><p>Гарантийное обслуживание и ремонт</p></a>');
    document.write('                    </div>');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Об автосалоне</p>');
    document.write('                        <a href="404.html"><p>Автосалон</p></a>');
    document.write('                        <a href="404.html"><p>Сотрудники</p></a>');
    document.write('                        <a href="404.html"><p>Новости</p></a>');
    document.write('                        <a href="partials/about.html"><p>Контакты</p></a>');
    document.write('                        <a href="https://yandex.ru/maps/?rtext=~53.869147, 27.530534"><p>Как добраться?</p></a>');
    document.write('                    </div>');
    document.write('                </div>');
    document.write('                <div class="main-links">');
    document.write('                    <a href="404.html"><p>Специальные предложения</p></a>');
    document.write('                    <a href="404.html"><p>Записаться на обслуживание</p></a>');
    document.write('                    <a href="partials/404.html"><p>Записаться на ремонт</p></a>');
    document.write('                    <a href="partials/support.html"><p>Служба клиентской поддержки</p></a>');
    document.write('                </div>');
    document.write('            </div>');
    document.write('            <div class="contacts-container">');
    document.write('                <div class="contacts-info">');
    document.write('                    <div class="contact-block">');
    document.write('                        <p>тел.</p>');
    document.write('                        <p>+375 (29) 865 79 68</p>');
    document.write('                    </div>');
    document.write('                    <div class="contact-block">');
    document.write('                        <p>Адрес</p>');
    document.write('                        <p>г. Минск, ул. Савицкого, д.3</p>');
    document.write('                    </div>');
    document.write('                </div>');
    document.write('                <div class="social-media">');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                </div>');
    document.write('            </div><p class="author">&#169; Басалай Олег</p>');
    document.write('        </div>');
    document.write('    </footer>');

}else{
    document.write('<footer>');
    document.write('        <div class="footer-container">');
    document.write('            <div class="links-container">');
    document.write('                <div class="links-row">');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Автомобили с пробегом</p>');
    document.write('                        <a href="404.html"><p>Автомобили с большим пробегом</p></a>');
    document.write('                        <a href="404.html"><p>Автомобили "как с салона"</p></a>');
    document.write('                        <a href="404.html"><p>Сервис Trade-In</p></a>');
    document.write('                    </div>');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Владельцам</p>');
    document.write('                        <a href="404.html"><p>Услуги сервиса</p></a>');
    document.write('                        <a href="404.html"><p>Запасные масла и расходники</p></a>');
    document.write('                        <a href="404.html"><p>Гарантийное обслуживание и ремонт</p></a>');
    document.write('                    </div>');
    document.write('                    <div class="link-column">');
    document.write('                        <p class="link-head">Об автосалоне</p>');
    document.write('                        <a href="404.html"><p>Автосалон</p></a>');
    document.write('                        <a href="404.html"><p>Сотрудники</p></a>');
    document.write('                        <a href="404.html"><p>Новости</p></a>');
    document.write('                        <a href="about.html"><p>Контакты</p></a>');
    document.write('                        <a href="https://yandex.ru/maps/?rtext=~53.869147, 27.530534"><p>Как добраться?</p></a>');
    document.write('                    </div>');
    document.write('                </div>');
    document.write('                <div class="main-links">');
    document.write('                    <a href="404.html"><p>Специальные предложения</p></a>');
    document.write('                    <a href="404.html"><p>Записаться на обслуживание</p></a>');
    document.write('                    <a href="404.html"><p>Записаться на ремонт</p></a>');
    document.write('                    <a href="support.html"><p>Служба клиентской поддержки</p></a>');
    document.write('                </div>');
    document.write('            </div>');
    document.write('            <div class="contacts-container">');
    document.write('                <div class="contacts-info">');
    document.write('                    <div class="contact-block">');
    document.write('                        <p>тел.</p>');
    document.write('                        <p>+375 (29) 865 79 68</p>');
    document.write('                    </div>');
    document.write('                    <div class="contact-block">');
    document.write('                        <p>Адрес</p>');
    document.write('                        <p>г. Минск, ул. Савицкого, д.3</p>');
    document.write('                    </div>');
    document.write('                </div>');
    document.write('                <div class="social-media">');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                    <div class="social-img"></div>');
    document.write('                </div>');
    document.write('            </div><p class="author">&#169; Басалай Олег</p>');
    document.write('        </div>');
    document.write('    </footer>');

}